INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'ELECTRONIC_ACTION_RPG', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/7/77/Mass_Effect_-_Legendary_Edition_-_Capa.jpg/250px-Mass_Effect_-_Legendary_Edition_-_Capa.jpg', 'Mass Effect: Legendary Edition é uma remasterização dos três primeiros jogos da série Mass Effect, desenvolvida pela BioWare e publicada pela Electronic Arts.', 'Mass Effect: Legendary Edition é uma remasterização dos três primeiros jogos da série Mass Effect, desenvolvida pela BioWare e publicada pela Electronic Arts.  A remasterização foi anunciada em 7 de novembro de 2020 e lançada em 14 de maio de 2021 para Microsoft Windows, PlayStation 4, Xbox One.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'ACTION_AND_ADVENTURE', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/e/e7/Red_Dead_Redemption_2.png/270px-Red_Dead_Redemption_2.png', 'Red Dead Redemption 2 (estilizado Red Dead Redemption II) é um jogo eletrônico de ação-aventura desenvolvido e publicado pela Rockstar Games', 'Red Dead Redemption 2 (estilizado Red Dead Redemption II) é um jogo eletrônico de ação-aventura desenvolvido e publicado pela Rockstar Games. É o terceiro título da série Red Dead e uma prequela de Red Dead Redemption, tendo sido lançado em outubro de 2018 para PlayStation 4 e Xbox One e em novembro de 2019 para Microsoft Windows e Google Stadia. A história se passa em 1899 em uma representação ficcional do oeste, meio-oeste e sul dos Estados Unidos e acompanha o fora da lei Arthur Morgan, que precisa lidar com o declínio do Velho Oeste e sobreviver à perseguição de forças governamentais, gangues rivais e outros adversários.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'ELECTRONIC_ACTION_RPG', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/06/TW3_Wild_Hunt.png/270px-TW3_Wild_Hunt.png', 'The Witcher 3: Wild Hunt (em polonês: Wiedźmin 3: Dziki Gon) é um jogo eletrônico de RPG de ação em mundo aberto desenvolvido pela CD Projekt RED', 'The Witcher 3: Wild Hunt (em polonês: Wiedźmin 3: Dziki Gon) é um jogo eletrônico de RPG de ação em mundo aberto desenvolvido pela CD Projekt RED e lançado no dia 19 de maio de 2015 para as plataformas Microsoft Windows, PlayStation 4, Xbox One e em outubro de 2019 para o Nintendo Switch, sendo o terceiro título da série de jogos The Witcher. Ele sucede The Witcher (2007) e The Witcher 2: Assassins of Kings (2011), que foram baseados na série de livros de fantasia Wiedźmin, do escritor polonês Andrzej Sapkowski.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'ACTION_AND_ADVENTURE', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/7/7b/Sekiro_Shadows_Die_Twice_capa.png/270px-Sekiro_Shadows_Die_Twice_capa.png', 'Sekiro: Shadows Die Twice (セキロ：シャドウズ ダイ トゥワイス Sekiro: Shadōzu Dai Towaisu?) é um jogo eletrônico de ação-aventura desenvolvido pela FromSoftware e publicado pela Activision.', 'Sekiro: Shadows Die Twice (セキロ：シャドウズ ダイ トゥワイス Sekiro: Shadōzu Dai Towaisu?) é um jogo eletrônico de ação-aventura desenvolvido pela FromSoftware e publicado pela Activision. Foi lançado em 22 de março de 2019 para Microsoft Windows, PlayStation 4 e Xbox One, e em 28 de outubro de 2020 para Google Stadia. O jogo se passa em uma versão mágica e fictícia do período Sengoku no Japão, e segue um shinobi que tenta se vingar de um clã samurai que o atacou e sequestrou seu lorde.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'ELECTRONIC_ACTION_RPG', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/d/dc/Ghost_of_Tsushima_capa.png/270px-Ghost_of_Tsushima_capa.png', 'Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment.', 'Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment. A história acompanha Jin Sakai, um samurai que precisa proteger a Ilha de Tsushima durante a primeira invasão mongol do Japão. Ele se vê dividido entre escolher seguir o código do guerreiro para lutar honradamente ou usar métodos práticos e desonrosos para subjugar os mongóis. A jogabilidade apresenta um grande mundo aberto que pode ser explorado a pé ou a cavalo. Ao enfrentar inimigos o jogador pode escolher enfrentá-los diretamente com a katana de Jin ou usar táticas furtivas e assassinar oponentes tornando-se assim o lendário guerreiro conhecido como "o Fantasma". Um modo multijogador intitulado Ghost of Tsushima: Legends foi lançado posteriormente e disponibilizado em separado do jogo principal.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'PLATFORM', 'SUPER_SNES_AND_PC', 'https://upload.wikimedia.org/wikipedia/pt/thumb/a/a1/Hollow_Knight_Cover.jpg/200px-Hollow_Knight_Cover.jpg', 'Hollow Knight é um jogo indie de gênero metroidvania desenvolvido e publicado pela Team Cherry, lançado para Microsoft Windows, macOS e Linux em 2017 e, posteriormente, para Nintendo Switch, Playstation 4 e Xbox One em 2018', 'Hollow Knight é um jogo indie de gênero metroidvania desenvolvido e publicado pela Team Cherry, lançado para Microsoft Windows, macOS e Linux em 2017 e, posteriormente, para Nintendo Switch, Playstation 4 e Xbox One em 2018. O seu desenvolvimento foi sustentado através de uma campanha no Kickstarter, onde arrecadou cerca de AU$57.000 até o final de 2014.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'PLATFORM', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/a/a1/Hollow_Knight_Cover.jpg/200px-Hollow_Knight_Cover.jpg', 'Hollow Knight é um jogo indie de gênero metroidvania desenvolvido e publicado pela Team Cherry, lançado para Microsoft Windows, macOS e Linux em 2017 e, posteriormente, para Nintendo Switch, Playstation 4 e Xbox One em 2018.', 'Hollow Knight é um jogo indie de gênero metroidvania desenvolvido e publicado pela Team Cherry, lançado para Microsoft Windows, macOS e Linux em 2017 e, posteriormente, para Nintendo Switch, Playstation 4 e Xbox One em 2018. O seu desenvolvimento foi sustentado através de uma campanha no Kickstarter, onde arrecadou cerca de AU$57.000 até o final de 2014. No jogo, um cavaleiro sem nome explora um reino em ruínas habitado por insetos, desbloqueando habilidades novas que ajudam a explorar e livrar o reino de uma infecção causada por um deus esquecido.Até o início de 2019, Hollow Knight havia vendido 2,800,000 de cópias no mundo inteiro. Uma sequência chamada Hollow Knight: Silksong está em desenvolvimento desde 2019.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'PLATFORM', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/3/3b/OriandtheBlindForestCapa.jpg/250px-OriandtheBlindForestCapa.jpg', 'Ori and the Blind Forest é um jogo eletrônico de aventura em plataforma desenvolvido pela Moon Studios e publicado pela Microsoft Studios para Xbox One e Windows 10 no dia 11 de março de 2015. No dia 27 de Setembro de 2019, também foi lançado para o Nintendo Switch.', 'Ori and the Blind Forest é um jogo eletrônico de aventura em plataforma desenvolvido pela Moon Studios e publicado pela Microsoft Studios para Xbox One e Windows 10 no dia 11 de março de 2015. No dia 27 de Setembro de 2019, também foi lançado para o Nintendo Switch. o jogo, o jogador assume o controle de Ori, um espírito branco guardião, e Sein, a "luz e olhos" do Espírito da Árvore na Floresta. Para progredir na história, os jogadores devem mover entre plataformas e solucionar quebra-cabeças. O jogo apresenta um sistema chamada "ligações da alma", que permite ao jogador salvar seu progresso quando desejar, e um sistema de melhoras que dá aos jogadores a habilidade de evoluir as técnicas e poderes de Ori.Foi desenvolvido pela Moon Studios e adquirido pela Xbox Game Studios um ano depois do começo de seu desenvolvimento. A história do jogo foi inspirada em O Rei Leão e O Gigante de Ferro, enquanto que parte dos elementos da jogabilidade foram inspirados pelas franquias Rayman e Metroid.Em seu lançamento, Ori and the Blind Forest recebeu aclamação crítica, com os jogadores elogiando sua jogabilidade, direção de arte, história, sequências de ação, trilha sonora e design de ambiente. Gennadiy Korol, cofundador da Moon Studios, disse que o jogo foi lucrativo para companhia dentro de poucas semanas após seu lançamento. Em 2017, uma sequência chamada Ori and the Will of the Wisps foi anunciada na E3.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'PLATFORM', 'MULTIPLE_PLATFORMS', 'https://upload.wikimedia.org/wikipedia/pt/thumb/c/c1/Cuphead_capa.png/270px-Cuphead_capa.png', 'Cuphead é um jogo eletrônico de run and gun e plataforma criado pelos irmãos canadenses Chad e Jared Moldenhauer através da Studio MDHR.', 'Cuphead é um jogo eletrônico de run and gun e plataforma criado pelos irmãos canadenses Chad e Jared Moldenhauer através da Studio MDHR. O jogo foi inspirado no estilo de animação Rubber hose (em português, "mangueira de borracha") usado em desenhos animados da Era de Ouro da animação americana, como o trabalho dos estúdios Fleischer Studios, Warner Bros. Cartoons e Walt Disney Animation Studios, procurando manter a obra em qualidades subversivas e surrealistas. O jogo foi lançado em 29 de setembro de 2017 para Xbox One e Microsoft Windows.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic the Hedgehog CD', 4, 1993, 'PLATFORM', 'SEGA_CD_AND_PC', 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/17/Sonic_CD_capa.png/270px-Sonic_CD_capa.png', 'Sonic the Hedgehog CD (ソニック・ザ・ヘッジホッグCD Sonikku za Hejjihoggu Shī Dī?) é um jogo eletrônico da série Sonic the Hedgehog, lançado para Sega CD em 1993 e para computadores pessoais em 1995. ', 'Sonic the Hedgehog CD é um jogo eletrônico da série Sonic the Hedgehog, lançado para Sega CD em 1993 e para computadores pessoais em 1995. Foi relançado em dezembro de 2011 em alta resolução para o Xbox Live Arcade, Playstation Network, computadores, iOS, e Android, em 14 de Novembro de 2012, para o Windows Phone 7 e 8, e em agosto de 2013 chega para o console Ouya. Sua ultima versão se encontra dentro da coletânea Sonic Origins, lançada em 2022 para o PC (via Steam e Epic Games Store) e consoles da oitava e nona geração. Nas versões em HD, é possível jogar com Tails, e em Origins, com Knuckles e Amy (após o lançamento da DLC Plus).');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);